INSERT INTO tItems VALUES('XXXXXXXX', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 'YOUR_DESCRIPTION_HERE', 'YOUR_IMAGE_HERE');

/* statement to use for an insert with default empty description and image */
INSERT INTO tItems VALUES('XXXXXXXX', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', DEFAULT(description), DEFAULT(image));
